version: "3.7"
services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "80:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/proxy.conf:/etc/nginx/proxy.conf
      - ./nginx/map.conf:/etc/nginx/map.conf
    
  git-activity-fetcher:
    image: ${REGISTRY_LOGIN_SERVER:-registryaurora.azurecr.io}/git-activity-fetcher:${GIT_ACTIVITY_FETCHER_TAG}
    container_name: github-api-fetcher
    restart: always
    ports:
      - "3000:3000"
    environment:
      - GITHUB_ACCESS_TOKEN=${GITHUB_ACCESS_TOKEN}

  random-http-status:
    image: solsson/httpstatus-random
    container_name: random-http-status
    restart: always
    ports:
      - "3001:8080"
    