version: "3.7"
services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "${NGINX_PORT}:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/proxy.conf:/etc/nginx/proxy.conf
      - ./nginx/map.conf:/etc/nginx/map.conf
      - /etc/letsencrypt:/etc/letsencrypt

  dockerized-db:
    image: northamerica-northeast1-docker.pkg.dev/aurora-377318/main-registry/dockerized-db:${DOCKERIZED_DB_TAG}
    container_name: postgres
    hostname: postgres-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DB_SUPERUSER_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    # volumes:
    #   - /var/postgres-data:/var/lib/postgresql/data

  git-activity-fetcher:
    image: northamerica-northeast1-docker.pkg.dev/aurora-377318/main-registry/git-activity-fetcher:${GIT_ACTIVITY_FETCHER_TAG}
    container_name: github-api-fetcher
    hostname: git
    depends_on:
      - dockerized-db
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}_git
      - DB_PASSWORD={DB_PASSWORD}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - CORS_WHITELIST=${CORS_WHITELIST}

  expenses:
    image: northamerica-northeast1-docker.pkg.dev/aurora-377318/main-registry/expenses:${EXPENSES_TAG}
    container_name: expenses
    hostname: expenses
    depends_on:
      - dockerized-db
    restart: always
    ports:
      - "3001:3001"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}_expenses
      - DB_PASSWORD={DB_PASSWORD}
      - ORGANIZATION_HOST={ORGANIZATION_HOST}
      - TIMESHEET_HOST=${TIMESHEET_HOST}
      - CORS_WHITELIST=${CORS_WHITELIST}
  
  timesheet:
    image: northamerica-northeast1-docker.pkg.dev/aurora-377318/main-registry/timesheet:${TIMESHEET_TAG}
    container_name: timesheet
    hostname: timesheet
    depends_on:
      - dockerized-db
    restart: always
    ports:
      - "3003:3003"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}_timesheet
      - DB_PASSWORD={DB_PASSWORD}
      - CORS_WHITELIST=${CORS_WHITELIST}
      - ORGANIZATION_HOST=${ORGANIZATION_HOST}
      - EXPENSES_HOST=${EXPENSES_HOST}
    
  organization:
    image: northamerica-northeast1-docker.pkg.dev/aurora-377318/main-registry/organization:${ORGANIZATION_TAG}
    container_name: organization
    hostname: organization
    depends_on:
      - dockerized-db
    restart: always
    ports:
      - "3002:3002"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}_organization
      - DB_PASSWORD={DB_PASSWORD}
      - CORS_WHITELIST=${CORS_WHITELIST}
      - TIMESHEET_HOST=${TIMESHEET_HOST}
      - EXPENSES_HOST=${EXPENSES_HOST}
  
  adminsdk:
    image: northamerica-northeast1-docker.pkg.dev/aurora-377318/main-registry/adminsdk:${ADMINSDK_TAG}
    container_name: adminsdk
    restart: always
    ports:
      - "8010:8010"
    volumes:
      - ./credentials.json:/usr/src/app/credentials.json
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/usr/src/app/credentials.json
      - CORS_WHITELIST=${CORS_WHITELIST}

  payments:
    image: northamerica-northeast1-docker.pkg.dev/aurora-377318/main-registry/payments:${PAYMENTS_TAG}
    container_name: payments
    depends_on:
      - dockerized-db
    restart: always
    ports:
      - "3005:3005"
    environment:
      - CORS_WHITELIST=${CORS_WHITELIST}
    
