service:
  name: timesheet
  port: 3003
  image:
    name: northamerica-northeast1-docker.pkg.dev/aurora-377318/main-registry/timesheet
    tag: 60501d2d0b40bdf6ec1e4ef42e89103977b8899a
  namespace: dev
  replicas: 
    max: 10
    min: 1