name: docker_build_push_acr
 
on:
  workflow_call:
    secrets:
      GCP_CREDENTIALS:
        required: true
      REGISTRY_SERVER:
        required: true
    
 
jobs:
  docker_build_push_acr:
    name: 'Docker Build and Push to GCR'
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: 'read'
      id-token: 'write'
    defaults:
      run:
        shell: bash
  
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: 'Authenticating to GCP' 
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}
    
    - name: 'Setup gcloud SDK'
      uses: google-github-actions/setup-gcloud@v1
  
    - name: 'Configure Docker to use the gcloud command-line tool as a credential helper'
      run: | 
        gcloud auth configure-docker --quiet

    - name: 'Build and push Docker image'
      run: |
        docker build . -t ${{ secrets.REGISTRY_SERVER}}/${{ github.event.repository.name }}:${{ github.sha }}
        docker push ${{ secrets.REGISTRY_SERVER}}/${{ github.event.repository.name }}:${{ github.sha }}