name: docker_build_push_acr
 
on:
  workflow_call:
    secrets:
      REGISTRY_REPOSITORY:
        required: true
    
jobs:
  docker_build_push_acr:
    name: 'Docker Build and Push to GCR'
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: 'read'
      id-token: 'write'
    defaults:
      run:
        shell: bash
  
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3
    
    - id: 'auth'
      name: 'Authenticating to GCP' 
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: projects/781206613588/locations/global/workloadIdentityPools/my-pool/providers/my-provider
        service_account: gitops-service-account@aurora-377318.iam.gserviceaccount.com
        token_format: 'access_token'
    
    - name: 'setup docker login'
      run | 
        gcloud auth configure-docker northamerica-northeast1-docker.pkg.dev

    - name: 'Build and push Docker image to Google Artifact Registry'
      run: |
        docker build -t northamerica-northeast1-docker.pkg.dev/aurora-377318/${{ secrets.REGISTRy_REPOSITORY }}/${{ github.event.repository.name }}:${{ github.sha }} .
        docker push northamerica-northeast1-docker.pkg.dev/aurora-377318/${{ secrets.REGISTRy_REPOSITORY }}/${{ github.event.repository.name }}:${{ github.sha }}
