name: 'build docker image and store it as an artifact'

on:
  workflow_call:
    inputs:
      SERVICE_LANGUAGE:
        description: 'Programming language of the service'
        required: true
        type: string
    secrets:
      GITOPS_PRIVATE_SSH_KEY:
        description: 'SSH key to access GitOps repository'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Gitops
        uses: actions/checkout@v3
        with:
          path: gitops
          repository: Aurora-UdeS/GitOps
          ssh-key: ${{ secrets.GITOPS_PRIVATE_SSH_KEY }}

      - name: Checkout Service
        uses: actions/checkout@v3
        with:
          path: service

      - name: 'Authenticating to GCP' 
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: projects/781206613588/locations/global/workloadIdentityPools/my-pool/providers/my-provider
          service_account: gitops-service-account@aurora-377318.iam.gserviceaccount.com
          
      - name: 'Setup docker login'
        run: | 
          gcloud auth configure-docker northamerica-northeast1-docker.pkg.dev

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and export
        uses: docker/build-push-action@v4
        with:
          file: gitops/${{ inputs.SERVICE_LANGUAGE }}/Dockerfile
          context: .
          build-contexts: |
            service=service
            gitops=gitops/${{ inputs.SERVICE_LANGUAGE }}
          tags: northamerica-northeast1-docker.pkg.dev/aurora-377318/main-registry/${{ github.event.repository.name }}:${{ github.sha }}
          push: true