name: deploy_to_linux_vm

on:
  workflow_call:
    secrets:
      SSH_PRIVATE_KEY:
        required: true
      GITOPS_PRIVATE_SSH_KEY:
        required: true
    inputs:
      SERVICE_NAME:
        description: 'Name of the service to deploy'
        default: ''
        type: string
        required: true

jobs:
  update_container_tag:
    name: update_container_tag
    runs-on: ubuntu-latest
    steps:
      - name: chekcout
        uses: actions/checkout@v3
        with:
          repository: Aurora-UdeS/GitOps
          ssh-key: ${{ secrets.GITOPS_PRIVATE_SSH_KEY }}
      - name: update_container_tag
        run: |
          sed -i "s/${{ inputs.SERVICE_NAME }}_TAG=.*/${{ inputs.SERVICE_NAME }}_TAG=${{ github.sha }}/" .env
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Updated container tag to ${{ github.sha }}"
          git push
  deploy_to_linux_vm:
    name: deploy_to_linux_vm
    runs-on: ubuntu-latest
    needs: update_container_tag
    steps:
      - name: Setup SSH Keys and known_hosts
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
      - name: Deploy to Linux VM
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
          USER: azureuser
          HOST: aurora-dev.eastus.cloudapp.azure.com
        run: |
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i $SSH_AUTH_SOCK $USER@$HOST "cd /home/${USER}/GitOps && git pull && sudo docker compose up -d --build"
  