name: deploy_to_linux_vm

on:
  workflow_call:
    secrets:
      GITOPS_PRIVATE_SSH_KEY:
        required: true
    inputs:
      SERVICE_NAME:
        description: 'Name of the service to deploy'
        default: ''
        type: string
        required: true

jobs:
  update_container_tag:
    name: 'update container tag'
    runs-on: self-hosted

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          repository: Aurora-UdeS/GitOps
          ssh-key: ${{ secrets.GITOPS_PRIVATE_SSH_KEY }}
      - name: 'update container tag'
        run: |
          sed -i "s/${{ inputs.SERVICE_NAME }}_TAG=.*/${{ inputs.SERVICE_NAME }}_TAG=${{ github.sha }}/" .env
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit --allow-empty -m "Updated container tag to ${{ github.sha }}"
          git push
  deploy_to_linux_vm:
    name: 'Deploy to linux vm'
    runs-on: self-hosted
    needs: update_container_tag
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
        with:
          repository: Aurora-UdeS/GitOps
          ssh-key: ${{ secrets.GITOPS_PRIVATE_SSH_KEY }}
      - name: GCP Auth
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: projects/781206613588/locations/global/workloadIdentityPools/my-pool/providers/my-provider
          service_account: gitops-service-account@aurora-377318.iam.gserviceaccount.com
      - name: 'setup docker login'
        run: | 
          gcloud auth configure-docker northamerica-northeast1-docker.pkg.dev
      - name: 'Deploy to Linux VM'
        run: |
          gcloud compute ssh --zone "northamerica-northeast1-a" "runner@main" --command "cd ~/GitOps && ./deploy.sh dev" -- -t
  
